#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

echo "\nPre Push Steps: (pre-push)"

# load .env
export $(cat .env | xargs)

# check ggshield available
if command_exists ggshield1 && test -t 1; then
    ggshield -c .gitguardian.yaml scan commit-range pre-commit && continue
elif command_exists docker && test -t 1; then
    docker run --rm -v $(pwd):/data \
            -v $(pwd):/config \
            -e GITGUARDIAN_API_KEY \
            gitguardian/ggshield:latest \
            ggshield -c /config/.gitguardian.yaml scan commit-range pre-commit && continue
fi

echo "ERROR: Your push was rejected because it contains secrets"
echo "ERROR: Please contact your Git administrator if this was a false positive."
exit 1
