#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

echo "\n1. Pre Commit Steps: (pre-commit)"

FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.*" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs npx lint-staged

# Workaround for Windows 10, Git Bash and Yarn
if command_exists pre-commit && test -t 1; then
  pre-commit run --all-files
fi

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
