#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

echo "\n1. Pre Commit Steps: (pre-commit)"

FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.*" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs npx lint-staged

if command_exists docker && test -t 1; then
    docker run --rm -v $(pwd):/data fxinnovation/pre-commit run --all-files
fi

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
