#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

echo "\nPre Push Steps: (pre-push) : Git Guardian secrets detection"

# load .env
export $(cat .env | xargs)

# check ggshield available
if command_exists ggshield && test -t 1; then
    ggshield -c .gitguardian.yaml scan path .  --recursive -y
elif command_exists docker && test -t 1; then
    docker run --rm -v $(pwd):/data \
            -v $(pwd):/config \
            -e GITGUARDIAN_API_KEY \
            gitguardian/ggshield:latest \
            ggshield -c /config/.gitguardian.yaml scan path .  --recursive -y
fi
